[package]
name = "bixat_screen_recorder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
scap = "0.0.8"

[build-dependencies]
cc = "1.0"
